### ISSUE TITLE
README file edits

### ISSUE THREAD

**Issue by claudiol** [mikthoma/ocpag-repo#18]
Small edit on the command detailed in the README file:

Change from: ansible-playbook generate.yml --extra-args "@my_variables.yml"
Change to    : ansible-playbook generate.yml --extra-vars "@my_variables.yml"

**Comment by ckupe** [comment]
These requests were addressed in https://github.com/mikthoma/ocpag-repo/commit/cdc9ad09513646b6ba33988bb95e7b70b2a70c24
