### ISSUE TITLE
Offline bundle details in README 

### ISSUE THREAD

**Issue by claudiol** [mikthoma/ocpag-repo#20]
We need to add verbiage on what the bundle includes for each target.

Example verbiage should include

- Component Name
- Description
- URL Location

> oc Command Line Interface (CLI) tool | OpenShift CLI tool used to mirror required images, create applications and manage OpenShift Container Platform projects from a terminal | http://mirror.openshift.com/pub/openshift-v4/clients/ocp

> Red Hat CoreOS image | RHCOS is the only supported operating system for OpenShift Container Platform control plane, or master, machines. RHCOS is the default operating system for all cluster machines. | http://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/latest/latest

> OpenShift Images | Official OpenShift release images | quay.io/openshift-release-dev/ocp-release:$OCP_VERSION-x86_64NOTE: You will need to use the oc command to mirror the image contents

> OpenShift Installer Command LIne Interface (CLI) - openshift-install | This is the binary that can then be invoked to create an OpenShift cluster | Extracted from the OpenShift release images. NOTE: There is a direct relationship between this executable and the OCP release images.  If you use the wrong openshift-install executable it will lead to an unsuccessful deployment of OpenShift.

**Comment by ckupe** [comment]
https://github.com/mikthoma/ocpag-repo/commit/96db3d33efc53c9a91a342fb2ff0969488903d17 Should resolve this request.
